### ISSUE TITLE
att_to_description() can't deal with tests files

### ISSUE THREAD

**Issue by abichat** [ThinkR-open/attachment#10]
When using `att_to_description()`, it removes `{spelling}` from `Suggests` although it is used it in `tests/spelling.R` created by `use_spell_check()`. 

I tried `att_to_description(dir.v = c("vignettes", "tests"))` but doesn't work. 

`att_to_description(extra.suggests = "spelling")` works but it will not be convenient with more packages used only in `tests/`.

**Comment by statnmap** [comment]
Now it works with `att_to_description(dir.t = "tests")` available by default.
