### ISSUE TITLE
Package in `data("example", package = "mypkgperso")` not detected

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/attachment#104]
## Validation

Run :

```r
  tmpdir <- tempfile("dummysuggestdata")
  dir.create(tmpdir)
  file.copy(system.file("dummypackage",package = "attachment"), tmpdir, recursive = TRUE)
  dummypackage <- file.path(tmpdir, "dummypackage")

attachment::att_amend_desc(path = dummypackage, check_if_suggests_is_installed = FALSE)
readLines(file.path(dummypackage, "DESCRIPTION"))
```

- [x] att_amend_desc() adds the dependencies of a package only used for its data like in examples:

{stringr} is used in example of my_mean.R :

![image](https://github.com/user-attachments/assets/6a7e03e1-ed49-47fb-abcc-c58128029ff9)

=> {stringr} has added in Suggest

![image](https://github.com/user-attachments/assets/512e49be-625b-46c4-9db2-c5280c2e5008)

**Comment by MurielleDelmotte** [comment]
validate
