### ISSUE TITLE
Failure with dev roxygen2

### ISSUE THREAD

**Issue by hadley** [ThinkR-open/attachment#107]
roxygen2 now uses messages instead of warnings so the tests fail. I would have attempted a fix, but I don't understand how your package code is generated.

```
Running ‘testthat.R’
Running the tests in ‘tests/testthat.R’ failed.
Complete output:
> library(testthat)
> library(attachment)
> 
> test_check("attachment")
Saving attachment parameters to yaml config file
Loading required namespace: rstudioapi
Updating dummypackage documentation
...

══ Failed tests ════════════════════════════════════════════════════════════════
── Failure ('test-att_from_namespace.R:92:5'): bad namespace can be corrected ──
`att_amend_desc(dummypackage)` did not throw the expected warning.
── Failure ('test-att_from_namespace.R:109:3'): bad namespace can be corrected ──
`att_from_namespace(...)` did not throw the expected warning.

[ FAIL 2 | WARN 0 | SKIP 2 | PASS 222 ]
Error: Test failures
Execution halted
```

## Validation

- [ ] tests pass with a version lower than 7.3.0

![image](https://github.com/ThinkR-open/attachment/assets/38312934/0bda7cea-f04b-4df4-8688-13dc6505d325)

- [ ] tests pass with a version higher than 7.3.0

![image](https://github.com/ThinkR-open/attachment/assets/38312934/1093035d-95f8-4455-af7f-644913f7ab6b)

**Comment by hadley** [comment]
Since I can't provide a fix and it's a busy time of the year, I'll push submission back to Jan 15. But please let me know if you can fix earlier or its ok to break on CRAN.

**Comment by statnmap** [comment]
Thanks for the warning.  
That's ok if it fails on CRAN. We plan to provide a fix by the end of January.

> Note that I understand how it can be confusing to mix development with {fusen} if you never used it before. However, you can always provide a fix the way you use to do in a classical package. The maintainer can then decide to re-generate it or not. The package structure keeps being a classical package structure. I'll try to make it clearer for future external contributions.

**Comment by hadley** [comment]
Thanks!

**Comment by statnmap** [comment]
A new version is now on CRAN.
