### ISSUE TITLE
Namespace not created if dont exists

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/attachment#32]
If the NAMESPACE is deleted, {attachment} does not re-create it.  
Need to run devtools::document() to do so ?

**Comment by VincentGuyader** [comment]
`attachement::att_amend_desc() ` should delete `NAMESPACE` then run `roxygen2::roxygenise()`  then do his job :)


to avoid issue with missing `NAMESPACE` and corrupted `NAMESPACE`

**Comment by VincentGuyader** [comment]
not fixed yet.

step to reproduce : 
-  create a {golem} (or a package)
- erase NAMESPACE
- run attachment::att_amend_desc()

-> no NAMESPACE created

**Comment by statnmap** [comment]
I found why. I am on it.

**Comment by statnmap** [comment]
This should work now, for both DESCRIPTION and NAMESPACE missing, if and only if parameter `document=TRUE`
![image](https://user-images.githubusercontent.com/21193866/124708364-791bfe00-defa-11eb-887d-6b750e7bdd3a.png)

Please tell me.
