### ISSUE TITLE
install_if_missing is not compatible with renv

### ISSUE THREAD

**Issue by VincentGuyader** [ThinkR-open/attachment#45]
after `renv::activate()`  `install_if_missing()` will not detect missing pacakge. 

because `find.package` dont use {renv} libPaths 

see :

![image](https://user-images.githubusercontent.com/10470699/152063769-d8407d6c-3ba1-4711-bf53-020139b4eea6.png)

**Comment by VincentGuyader** [comment]
we can do : 

` already_installed <- basename(try(find.package(to_be_installed, quiet = TRUE,lib.loc = .libPaths()), silent = TRUE))`

**Comment by statnmap** [comment]
Closed with https://github.com/ThinkR-open/attachment/commit/60fa932f099b82a95d04d82cf0dbd652299a0816
