### ISSUE TITLE
Deal with local package dependencies in find_remotes()

### ISSUE THREAD

**Issue by MurielleDelmotte** [ThinkR-open/attachment#54]
For now in `extract_pkg_info()`,

- [ ] local package is not specifically treated. It is guess with this `if()`:  
https://github.com/ThinkR-open/attachment/blob/ab906f92d895048e6f60a7065ef7044d6f1e2098/R/att_to_description.R#L485

## What is desired ?

_DESCRIPTION_
```
Imports:
    mylocalpackage
Remotes:
    local::mylocalpackage
```

## Technically

To test:

- [x] `remotes::install_local( )` from path to compressed file
- [x] `remotes::install_local( )` from path to local directory
- [x] Recovering the content of the files DESCRIPTION
- [x] Create a `fake_desc_local`

**Comment by statnmap** [comment]
Added in https://github.com/ThinkR-open/attachment/pull/57
