### ISSUE TITLE
Deal with git package dependencies in find_remotes() 

### ISSUE THREAD

**Issue by MurielleDelmotte** [ThinkR-open/attachment#55]
For now in `extract_pkg_info()`,

- [ ] url git package is not specifically treated. It is guess with this `if()`:  
https://github.com/ThinkR-open/attachment/blob/ab906f92d895048e6f60a7065ef7044d6f1e2098/R/att_to_description.R#L485

## What is desired (for examples)?

_DESCRIPTION_
```
Imports:
    lsr,
    igraph
Remotes:
    git::git@bitbucket.org:djnavarro/lsr.git,
    git::https://github.com/igraph/rigraph.git@main
```

**Comment by MurielleDelmotte** [comment]
Warning: 
RemoteType changes depending on the personal git

Idea to test: 
- RemoteType != (github/gitlab/bitbucket/local) & "git" detected in RemoteURL :
```
Remotes:
    git::
```

**Comment by statnmap** [comment]
Added in https://github.com/ThinkR-open/attachment/pull/60/
