### ISSUE TITLE
As dev, I want create_dependencies_file() to take other sources into account

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/attachment#56]
`create_dependencies_file()` uses DESCRIPTION as source of information.
_Note that DESCRIPTION file can be auto-fill using  `find_remotes()`

## Criteria of success

- [ ] If my DESCRIPTION contains 
```
Depends:
    mylocalpackage
Remotes:
    local::mylocalpackage
```
Then "dependencies_file.R" should looks like this

_output_
```r
# Remotes ----
install.packages("remotes")
remotes::install_local('mylocalpackage')
# Attachments ----
to_install <- c("cli", "config", "DBI", "dplyr", "glue", "golem", "htmltools", "knitr", "mylocalpackage", "magrittr", "purrr", "readr", "readxl", "rmarkdown", "shiny", "shinythemes", "stringdist", "stringr", "tibble", "tidyr", "writexl")
  for (i in to_install) {
    message(paste("looking for ", i))
    if (!requireNamespace(i)) {
      message(paste("     installing", i))
      install.packages(i)
    }
  }
```

And NOT like today:
```
# Remotes ----
install.packages("remotes")
remotes::install_github('local::mylocalpackage')
# Attachments ----
to_install <- c("cli", "config", "DBI", "dplyr", "glue", "golem", "htmltools", "knitr", "mylocalpackage", "magrittr", "purrr", "readr", "readxl", "rmarkdown", "shiny", "shinythemes", "stringdist", "stringr", "tibble", "tidyr", "writexl")
  for (i in to_install) {
    message(paste("looking for ", i))
    if (!requireNamespace(i)) {
      message(paste("     installing", i))
      install.packages(i)
    }
  }
```

## Technicals

- I think that listing all packages with their version with `install_version()` is not reliable, because of versions of sub-dependencies. I would recommend to redirect users to {renv} and create the Dockerfile using {renv}.
- At least, what is interesting is to list deps coming from GitHub, GitLab, etc... Except that `remotes::install_deps()` does read the DESCRIPTION correctly. Just need to use `set_remotes_to_desc()` during the process to be sure DESCRIPTION file is up-to-date.

**Comment by ExaminateurThinkR** [comment]
ok
