### ISSUE TITLE
Cannot install attachment: Removed from CRAN

### ISSUE THREAD

**Issue by shoeffner** [ThinkR-open/attachment#64]
I cannot install the current `attachment` package from CRAN.

```console
$ Rscript -e "install.packages('attachment', repos='http://cran.us.r-project.org')"
Warning message:
package ‘attachment’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```

Checking the project page https://cran.r-project.org/package=attachment, it seems the package was removed:

> Package ‘attachment’ was removed from the CRAN repository.
>
> Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/attachment).
>
> Archived on 2022-09-08 as check problems were not corrected in time.
> 
> A summary of the most recent check results can be obtained from the [check results archive](https://cran-archive.r-project.org/web/checks/2022/2022-09-08_check_results_attachment.html).
> 
> Please use the canonical form https://cran.r-project.org/package=attachment to link to this page.

The problem seems to be:

> Version: 0.2.5
> Check: for unstated dependencies in ‘tests’
> Result: WARN
>     Warning: unable to access index for repository https://bioconductor.org/packages/3.14/bioc/src/contrib:
>      cannot open URL 'https://bioconductor.org/packages/3.14/bioc/src/contrib/PACKAGES'
>     Warning: unable to access index for repository https://bioconductor.org/packages/3.14/data/annotation/src/contrib:
>      cannot open URL 'https://bioconductor.org/packages/3.14/data/annotation/src/contrib/PACKAGES'
>     Warning: unable to access index for repository https://bioconductor.org/packages/3.14/data/experiment/src/contrib:
>      cannot open URL 'https://bioconductor.org/packages/3.14/data/experiment/src/contrib/PACKAGES'
> Flavor: [r-oldrel-windows-ix86+x86_64](https://www.r-project.org/nosvn/R.check/r-oldrel-windows-ix86+x86_64/attachment-00check.html)

**Comment by statnmap** [comment]
I do not know why the package was removed.  
I had until 2022-09-27 to submit a new version.  
Also, I sent a new version yesterday, for which I have no answer...

**Comment by statnmap** [comment]
I would better recommend to use the r-universe.
You can add this in your Rprofile, or just before installing your packages, and it will be good. 
You will even have the last version, still not on CRAN

```r
options(repos = c(
  thinkropen = 'https://thinkr-open.r-universe.dev',
  CRAN = 'https://cloud.r-project.org'))
```

**Comment by statnmap** [comment]
Back to CRAN
