### ISSUE TITLE
As a dev, I would like a config file that stores parameters for `att_amend_desc()` 

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/attachment#75]
## Context

When I have a specific package, I change default parameters of `att_amend_desc()`, like `pkg_ignore` or `extra.suggest`. I'd like to be able to run `att_amend_desc()` directly in my console, but using my parameters, without having to go to the "dev_history" file where this line of code is written

## Validation

- [x]  I can run `att_amend_desc()` with parameters, and it replaces the config file

![Screenshot 2023-04-04 at 12 25 29](https://user-images.githubusercontent.com/54443785/229764065-990d2ac4-471b-42b2-b601-c4fffd968fcb.png)

- [x]  I can run `att_amend_desc(use.config = TRUE)` from anywhere, directly in the console, and it uses the last version of parameters of `att_amend_desc()` stored in a config file

(running the last chunk of the flat file `dev/flat_save_att_params.Rmd` both perform `inflate()` + `att_amend_dec()` with saved config :)
![Screenshot 2023-04-04 at 12 32 38](https://user-images.githubusercontent.com/54443785/229765916-d958d042-8edb-480e-a855-d72a0aacd124.png)

- [x] The user is informed about what is happening

(when updating config)
![image](https://user-images.githubusercontent.com/54443785/229766224-fbbc338a-6ffe-48cf-9a74-b241b2deca6e.png)

(when using config)
![image](https://user-images.githubusercontent.com/54443785/229765979-40fec731-241a-40fa-9ebd-f3de2c395973.png)

- [x] I  have the possibility to run a temporary version of `att_amend_desc()` with some parameters, without changing the config file (default behavior)

(e.g., removing two pkgs from suggest)
![Screenshot 2023-04-04 at 12 57 50](https://user-images.githubusercontent.com/54443785/229771464-8e6a5059-b2db-4d13-ad04-adc7a1137972.png)

## Tech 
- [x] `att_amend_desc()` has two new parameters named `update.config = FALSE` and `use.config = FALSE` by default

```{r}
#' @param update.config logical Should the list of parameter be saved for later use with use.config
#' @param use.config logical Should the att_amend_desc use the parameters saved in config
#' @param path.y character Path to yaml config file
```

**Comment by MurielleDelmotte** [comment]
Validate
