### ISSUE TITLE
As dev, I want create_dependencies_file() to have a parameter install_if_missing

### ISSUE THREAD

**Issue by MurielleDelmotte** [ThinkR-open/attachment#77]
`create_dependencies_file()` uses DESCRIPTION as source of information.
_Note that DESCRIPTION file can be auto-fill using  `find_remotes()`

## Criteria of success

- [x] create_dependencies_file() to have an ~`install_if_missing`~  `install_only_if_missing ` parameter

![image](https://user-images.githubusercontent.com/38312934/228774458-c8cd3721-1f6a-482d-b282-6cb42720902c.png)

- From a DESCRIPTION file such as:
![image](https://user-images.githubusercontent.com/38312934/228774892-1006e63c-bc72-4c2e-9d08-9056b5a9de95.png)

  - [ ] If install_if_missing  = FALSE (by default) , the installation instructions don't check, beforehand, if the packages are missing

![image](https://user-images.githubusercontent.com/38312934/228775126-5c1a1f04-2267-4dcc-8dca-4d6f4a75a7e9.png)

  - [ ] If install_if_missing  = TRUE (by default) , the installation instructions check, beforehand, if the packages are missing

![image](https://user-images.githubusercontent.com/38312934/228775233-c4af640f-fd42-4b8b-bda4-c2d231050bc7.png)

## Technicals

- [ ] Add a parameter `install_if_missing = FALSE` that will add a `if(requireNamespace(quietly = TRUE)) {}` before each install if the parameter is TRUE
```r
# Remotes ----
if(requireNamespace("remotes", quietly = TRUE)) {install.packages("remotes")}
if(requireNamespace("mylocalpackage", quietly = TRUE)) {remotes::install_github('local::mylocalpackage')}
...
```

- I think that listing all packages with their version with `install_version()` is not reliable, because of versions of sub-dependencies. I would recommend to redirect users to {renv} and create the Dockerfile using {renv}.
- It would be interesting to create the "socle" part of {dockerfiler} that install all deps, even without {renv}

**Comment by VincentGuyader** [comment]
ok, some improvment were made this the screenshot
