### ISSUE TITLE
As a Dev, I want to have all the instructions to check before submission to CRAN

### ISSUE THREAD

**Issue by MurielleDelmotte** [ThinkR-open/attachment#79]
As a Dev, I want to have all the instructions to check before submission to CRAN

## Criteria of success

 - [x] all the instructions to check before submission to CRAN are listed in the file dev_history

https://github.com/ThinkR-open/attachment/blob/fec563c89569988704ff553e6600258655b38dc7/dev/dev_history.R#L118

- [x]  The devtools::test() is successful

![image](https://user-images.githubusercontent.com/38312934/228263366-ecd4c17a-7023-4614-a3cf-96e5f76f0707.png)

- [x]   The testthat::test_dir("tests/testthat/") is successful

![image](https://user-images.githubusercontent.com/38312934/228263618-60170c9f-0714-46ab-bdb2-17f31ea06dd4.png)

## Technical

# Prepare for CRAN ----

pkgload::load_all()
devtools::test()
testthat::test_dir("tests/testthat/")

**Comment by statnmap** [comment]
Merci. 
Je valide.  
J'en profite pour fermer le ticket, car je pense qu'il n'y a pas d'action supplémentaire à réaliser.
