### ISSUE TITLE
deal with depend in yaml

### ISSUE THREAD

**Issue by VincentGuyader** [ThinkR-open/attachment#8]
![image](https://user-images.githubusercontent.com/10470699/49617291-50cf6a00-f9b4-11e8-8bb1-b7f2369c4f55.png)

**Comment by VincentGuyader** [comment]
here, `prettydoc` should be listed

**Comment by statnmap** [comment]
I used `knitr::purl` to extract R code from Rmd to avoid any conflict with what is written in the document.  
We can add a way to parse the yaml also

**Comment by ColinFay** [comment]
See the {yaml} package to do that: 
https://cran.r-project.org/web/packages/yaml/

**Comment by statnmap** [comment]
Added in e8a8f6a95caf0ef2c00f9261bc5331074e855249
