### ISSUE TITLE
As dev, I want create_dependencies_file() to use sub-functions to create the output to be used in dockerfiler::add_dockerfile()

### ISSUE THREAD

**Issue by MurielleDelmotte** [ThinkR-open/attachment#83]
`create_dependencies_file()` uses DESCRIPTION as source of information.
_Note that DESCRIPTION file can be auto-fill using  `find_remotes()`

## Criteria of success

- [x] A `dependencies_file_text()` exists and is tested

![image](https://user-images.githubusercontent.com/38312934/228802521-62be8da9-a862-4840-95d0-168d82004aa9.png)

- [x] It is used in `create_dependencies_file()` 

![image](https://user-images.githubusercontent.com/38312934/228802814-6b9419db-4132-4d3e-8ddf-9aca41e903e3.png)

- [x] `create_dependencies_file()` returns a list with the contents of `dependencies_file_text()` to be reused elsewhere

![image](https://user-images.githubusercontent.com/38312934/228803083-e6c67063-5c3e-42b3-9e17-bef3d0b5d5ed.png)

## Technicals

- [ ] I'd like to have a subfunction that would help create the output as follows to be used in `golem::add_dockerfile()` 

### ⚠️ fonction plus trop utilisée et qui utilisait : `dockerfiler::doc_from_desc()`

```r
# Remotes ----
install.packages("remotes")
remotes::install_github('local::mylocalpackage')
remotes::install_cran('cli')
remotes::install_cran('config')
...
```
- [ ]  I'd like to have a subfunction that would help create this other output as follows to be used in `dockerfiler::add_dockerfile()`
```r
# Remotes ----
install.packages("remotes")
remotes::install_github('local::mylocalpackage')
remotes::install_version('cli', version = "0.1.0")
remotes::install_version('config', version = "2.1.2")
...
```

- I think that listing all packages with their version with `install_version()` is not reliable, because of versions of sub-dependencies. I would recommend to redirect users to {renv} and create the Dockerfile using {renv}.
- It would be interesting to create the "socle" part of {dockerfiler} that install all deps, even without {renv}

**Comment by statnmap** [comment]
Perfect !
