### ISSUE TITLE
As dev, I want to improve create_dependencies_file() with the install_if_missing parameter

### ISSUE THREAD

**Issue by MurielleDelmotte** [ThinkR-open/attachment#85]
As a dev, I want to improve create_dependencies_file() so that the name of the install_if_missing parameter is more explicit

## Criteria of success

- [ ] The name of the parameter to check the presence of a package version is more explicit

![image](https://user-images.githubusercontent.com/38312934/229072467-daac399a-c84e-4362-8e96-e4fe22604fc4.png)

- [ ] the parameter changes the installation instruction of the remote package

![image](https://user-images.githubusercontent.com/38312934/229073018-fd7dc15d-b4ea-4477-b52a-0dda78f1d510.png)

## Technicals

- [x] replace install_if_missing -> install_only_if_missing
- [x] Modify dependencies_file to check also {remotes}

**Comment by VincentGuyader** [comment]
thanks
