### ISSUE TITLE
encoding issue

### ISSUE THREAD

**Issue by VincentGuyader** [ThinkR-open/attachment#9]
![image](https://user-images.githubusercontent.com/10470699/50594024-1ebe0480-0e9b-11e9-8526-d766cc54bc88.png)

**Comment by statnmap** [comment]
I added a parameter `encoding` in `att_from_rmd`, but not in `att_from_rmds` because only UTF-8 should be used. This parameter may be removed in the future.

A message from Yihui in `purl` function used in `att_from_rmd`:

> Warning message:
> In knit(..., tangle = TRUE) :
>   The encoding ("latin1") is not UTF-8. We will only support UTF-8 in the future. Please re-save your file "../test_encoding.Rmd" with the UTF-8 encoding. See [https://yihui.name/en/2018/11/biggest-regret-knitr/ ](https://yihui.name/en/2018/11/biggest-regret-knitr/) for more info.
