### ISSUE TITLE
As dev, I'd like a function to read `att_amend_desc()` parameters from a yaml file 

### ISSUE THREAD

**Issue by dagousket** [ThinkR-open/attachment#90]
As dev, I'd like a function to read `att_amend_desc()` parameters from a yaml file so that I can re-use them later on

## Validation

+ [x] a new fonction exist to load `att_amend_desc()` parameters from a yaml file

![image](https://user-images.githubusercontent.com/54443785/229545595-10588237-baaf-47bd-84ff-6f730f74f0d2.png)

=> https://github.com/ThinkR-open/attachment/blob/main/R/load_att_params.R

+ [x] when I call this function with a yaml file as input, it returns the named list of parameters

![image](https://user-images.githubusercontent.com/54443785/229545844-e676edb0-939a-4df9-85d0-addabe102d1d.png)

+ [x] if a yaml does not exist, it throws an error

![image](https://user-images.githubusercontent.com/54443785/229545968-d8864264-5d9d-4b36-94f1-487c31d13664.png)

+ [x] if yaml entries do not correspond to `att_amend_desc()` parameters, it throws an error

![image](https://user-images.githubusercontent.com/54443785/229546203-b135d30d-315b-4343-81d9-722ad336b6b0.png)

+ [x] when I call this function with a yaml file, it sends a message to the user to warn him which parameters have been loaded

![image](https://user-images.githubusercontent.com/54443785/229546549-aa338d9b-e307-46d5-920f-d8de8d7fabfb.png)

=> https://github.com/ThinkR-open/attachment/blob/main/tests/testthat/test-load_att_params.R

## Tech-Dev

+ [x] make a new function in flat for yaml param handling that takes a yaml and return a named list of parameters
+ [x] make unit test to read yaml
+ [x] avoid the use of additional dependencies, except for {yaml}
+ [x] make the function send the parameter loaded as message

**Comment by MurielleDelmotte** [comment]
Validate
