### ISSUE TITLE
As dev, I'd like to test the behavior of att_amend_desc() when using and updating config

### ISSUE THREAD

**Issue by dagousket** [ThinkR-open/attachment#92]
As dev, I'd like to test the behavior of att_amend_desc() when using and updating config, so that I make sure it will return an error in this case.

## Client validation

+ [x] a test exists to catch the error when `att_amend_desc(use.config = TRUE, update.config = TRUE)`

![image](https://user-images.githubusercontent.com/54443785/230001461-3c6609cf-8835-4ed9-b960-0d7597b39557.png)

=> https://github.com/ThinkR-open/attachment/blob/main/tests/testthat/test-amend-description.R

## Tech

+ [x] Add a test in `test-amend-description.R`

**Comment by MurielleDelmotte** [comment]
Validate
